package postgres

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/integraltech/brainsentry/internal/domain"
	"github.com/integraltech/brainsentry/pkg/tenant"
)

// ObservationRepository handles session observation persistence.
type ObservationRepository struct {
	pool *pgxpool.Pool
}

// NewObservationRepository creates a new ObservationRepository.
func NewObservationRepository(pool *pgxpool.Pool) *ObservationRepository {
	return &ObservationRepository{pool: pool}
}

// Create inserts a new session observation.
func (r *ObservationRepository) Create(ctx context.Context, obs *domain.SessionObservation) error {
	tenantID := tenant.FromContext(ctx)
	if obs.ID == "" {
		obs.ID = uuid.New().String()
	}
	obs.TenantID = tenantID
	obs.CreatedAt = time.Now()

	_, err := r.pool.Exec(ctx,
		`INSERT INTO session_observations (id, tenant_id, session_id, type, title, description, context, related_memory_id, created_at, auto_generated)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,
		obs.ID, obs.TenantID, obs.SessionID, obs.Type, obs.Title, obs.Description, obs.Context,
		nullIfEmpty(obs.RelatedMemoryID), obs.CreatedAt, obs.AutoGenerated,
	)
	if err != nil {
		return fmt.Errorf("inserting observation: %w", err)
	}
	return nil
}

// FindBySession returns observations for a session.
func (r *ObservationRepository) FindBySession(ctx context.Context, sessionID string) ([]domain.SessionObservation, error) {
	tenantID := tenant.FromContext(ctx)
	rows, err := r.pool.Query(ctx,
		`SELECT id, tenant_id, session_id, type, title, description, context, COALESCE(related_memory_id::text, ''), created_at, auto_generated
		FROM session_observations WHERE tenant_id = $1 AND session_id = $2 ORDER BY created_at DESC`,
		tenantID, sessionID)
	if err != nil {
		return nil, fmt.Errorf("finding observations: %w", err)
	}
	defer rows.Close()

	var observations []domain.SessionObservation
	for rows.Next() {
		var obs domain.SessionObservation
		if err := rows.Scan(&obs.ID, &obs.TenantID, &obs.SessionID, &obs.Type, &obs.Title,
			&obs.Description, &obs.Context, &obs.RelatedMemoryID, &obs.CreatedAt, &obs.AutoGenerated); err != nil {
			return nil, err
		}
		observations = append(observations, obs)
	}
	return observations, nil
}

// FindByType returns observations filtered by type across a tenant.
func (r *ObservationRepository) FindByType(ctx context.Context, obsType domain.ObservationType, limit int) ([]domain.SessionObservation, error) {
	tenantID := tenant.FromContext(ctx)
	if limit <= 0 {
		limit = 50
	}
	rows, err := r.pool.Query(ctx,
		`SELECT id, tenant_id, session_id, type, title, description, context, COALESCE(related_memory_id::text, ''), created_at, auto_generated
		FROM session_observations WHERE tenant_id = $1 AND type = $2 ORDER BY created_at DESC LIMIT $3`,
		tenantID, string(obsType), limit)
	if err != nil {
		return nil, fmt.Errorf("finding observations by type: %w", err)
	}
	defer rows.Close()

	var observations []domain.SessionObservation
	for rows.Next() {
		var obs domain.SessionObservation
		if err := rows.Scan(&obs.ID, &obs.TenantID, &obs.SessionID, &obs.Type, &obs.Title,
			&obs.Description, &obs.Context, &obs.RelatedMemoryID, &obs.CreatedAt, &obs.AutoGenerated); err != nil {
			return nil, err
		}
		observations = append(observations, obs)
	}
	return observations, nil
}

func nullIfEmpty(s string) any {
	if s == "" {
		return nil
	}
	return s
}
