package com.integraltech.brainsentry.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;

/**
 * Response containing hindsight note details.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class HindsightNoteResponse {

    private String id;
    private String tenantId;
    private String sessionId;

    // Note metadata (from Confucius spec)
    private String title;
    private String errorPattern;
    private String severity;  // NoteSeverity as string
    private String lastAccessedAt;  // Instant as string
    private Integer accessCount;

    // Error information
    private String errorType;
    private String errorMessage;
    private String errorContext;

    // Resolution
    private String resolution;
    private String resolutionSteps;
    private String resolutionReference;

    // Learning
    private String lessonsLearned;
    private String preventionStrategy;

    // Metadata
    private List<String> tags;
    private List<String> relatedMemoryIds;

    // Usage tracking
    private Integer occurrenceCount;
    private Integer referenceCount;
    private Integer preventionSuccessCount;
    private Double preventionEffectiveness;

    // Flags
    private Boolean autoGenerated;
    private Boolean preventionVerified;
    private Boolean frequent;
    private Boolean preventionEffective;

    // Timestamps
    private Instant createdAt;
    private Instant updatedAt;
    private Instant lastOccurrenceAt;

    private String createdBy;
    private String priority;
}
