package com.integraltech.brainsentry.repository;

import com.integraltech.brainsentry.domain.HindsightNote;
import com.integraltech.brainsentry.domain.enums.NoteSeverity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * JPA repository for HindsightNote entity.
 */
@Repository
public interface HindsightNoteJpaRepository extends JpaRepository<HindsightNote, String> {

    /**
     * Find all hindsight notes for a tenant.
     */
    List<HindsightNote> findByTenantId(String tenantId);

    /**
     * Find all hindsight notes for a tenant with pagination.
     */
    Page<HindsightNote> findByTenantId(String tenantId, Pageable pageable);

    /**
     * Find hindsight notes by session ID.
     */
    List<HindsightNote> findBySessionId(String sessionId);

    /**
     * Find hindsight notes by error type for a tenant.
     */
    List<HindsightNote> findByErrorTypeAndTenantId(String errorType, String tenantId);

    /**
     * Find hindsight notes containing keyword in error message.
     */
    List<HindsightNote> findByErrorMessageContainingAndTenantId(String keyword, String tenantId);

    /**
     * Find frequent errors (occurrenceCount > threshold).
     */
    List<HindsightNote> findByTenantIdAndOccurrenceCountGreaterThan(String tenantId, int threshold);

    /**
     * Find hindsight notes by priority.
     */
    List<HindsightNote> findByTenantIdAndPriority(String tenantId, String priority);

    /**
     * Find auto-generated notes.
     */
    List<HindsightNote> findByTenantIdAndAutoGeneratedTrue(String tenantId);

    /**
     * Find manually created notes.
     */
    List<HindsightNote> findByTenantIdAndAutoGeneratedFalse(String tenantId);

    /**
     * Search hindsight notes by error type or message keyword.
     */
    @Query("SELECT h FROM HindsightNote h WHERE h.tenantId = :tenantId " +
           "AND (h.errorType LIKE %:keyword% OR h.errorMessage LIKE %:keyword%)")
    List<HindsightNote> searchByKeyword(@Param("tenantId") String tenantId,
                                       @Param("keyword") String keyword);

    /**
     * Find hindsight notes created after a certain date.
     */
    List<HindsightNote> findByTenantIdAndCreatedAtAfter(String tenantId, Instant date);

    /**
     * Find hindsight notes with unverified prevention strategies.
     */
    List<HindsightNote> findByTenantIdAndPreventionVerifiedFalse(String tenantId);

    /**
     * Find hindsight notes ordered by occurrence count (most frequent first).
     */
    List<HindsightNote> findByTenantIdOrderByOccurrenceCountDesc(String tenantId);

    /**
     * Find hindsight notes ordered by reference count (most referenced first).
     */
    @Query("SELECT h FROM HindsightNote h WHERE h.tenantId = :tenantId ORDER BY h.referenceCount DESC")
    List<HindsightNote> findMostReferenced(@Param("tenantId") String tenantId);

    /**
     * Count hindsight notes by error type for a tenant.
     */
    @Query("SELECT h.errorType, COUNT(h) FROM HindsightNote h WHERE h.tenantId = :tenantId " +
           "GROUP BY h.errorType")
    List<Object[]> countByErrorType(@Param("tenantId") String tenantId);

    /**
     * Find recent errors (last N days).
     */
    @Query("SELECT h FROM HindsightNote h WHERE h.tenantId = :tenantId " +
           "AND h.lastOccurrenceAt > :since ORDER BY h.lastOccurrenceAt DESC")
    List<HindsightNote> findRecentErrors(@Param("tenantId") String tenantId,
                                       @Param("since") Instant since);

    /**
     * Check if a similar error already exists based on error type and message similarity.
     */
    @Query("SELECT h FROM HindsightNote h WHERE h.tenantId = :tenantId " +
           "AND h.errorType = :errorType " +
           "AND h.errorMessage LIKE %:messageSnippet%")
    List<HindsightNote> findSimilarErrors(@Param("tenantId") String tenantId,
                                          @Param("errorType") String errorType,
                                          @Param("messageSnippet") String messageSnippet);

    /**
     * Find hindsight notes by severity level for a tenant.
     */
    List<HindsightNote> findByTenantIdAndSeverity(String tenantId, NoteSeverity severity);

    /**
     * Find critical and high severity notes for a tenant.
     */
    @Query("SELECT h FROM HindsightNote h WHERE h.tenantId = :tenantId " +
           "AND h.severity IN ('CRITICAL', 'HIGH') " +
           "ORDER BY h.severity, h.lastOccurrenceAt DESC")
    List<HindsightNote> findCriticalByTenantId(@Param("tenantId") String tenantId);

    /**
     * Find most frequently accessed notes for a tenant.
     */
    @Query("SELECT h FROM HindsightNote h WHERE h.tenantId = :tenantId " +
           "ORDER BY h.accessCount DESC, h.lastAccessedAt DESC")
    List<HindsightNote> findMostAccessed(@Param("tenantId") String tenantId,
                                        Pageable pageable);

    /**
     * Find hindsight notes related to a specific note.
     * Graph relationship: HindsightNote -[:RELATED_TO]-> Note
     */
    @Query("SELECT h FROM HindsightNote h JOIN h.relatedNoteIds n WHERE n = :noteId AND h.tenantId = :tenantId")
    List<HindsightNote> findByRelatedNote(@Param("noteId") String noteId, @Param("tenantId") String tenantId);
}
