package service

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"github.com/integraltech/brainsentry/internal/domain"
	"github.com/integraltech/brainsentry/internal/dto"
	"github.com/integraltech/brainsentry/internal/repository/postgres"
	"github.com/integraltech/brainsentry/pkg/tenant"
)

// NoteTakingService handles session analysis and note generation.
type NoteTakingService struct {
	noteRepo        *postgres.NoteRepository
	auditRepo       *postgres.AuditRepository
	observationRepo *postgres.ObservationRepository
	openRouter      *OpenRouterService
	auditService    *AuditService
}

// NewNoteTakingService creates a new NoteTakingService.
func NewNoteTakingService(
	noteRepo *postgres.NoteRepository,
	auditRepo *postgres.AuditRepository,
	openRouter *OpenRouterService,
	auditService *AuditService,
	observationRepo *postgres.ObservationRepository,
) *NoteTakingService {
	return &NoteTakingService{
		noteRepo:        noteRepo,
		auditRepo:       auditRepo,
		observationRepo: observationRepo,
		openRouter:      openRouter,
		auditService:    auditService,
	}
}

// AnalyzeSession analyzes a session and extracts insights, decisions, and failures.
func (s *NoteTakingService) AnalyzeSession(ctx context.Context, req dto.SessionAnalysisRequest) (*dto.SessionAnalysisResponse, error) {
	tenantID := tenant.FromContext(ctx)
	if req.TenantID != "" {
		tenantID = req.TenantID
	}

	// Get audit logs for the session
	auditLogs, err := s.auditService.FindBySessionID(ctx, req.SessionID, 100)
	if err != nil {
		return nil, fmt.Errorf("fetching session audit logs: %w", err)
	}

	if len(auditLogs) == 0 {
		return &dto.SessionAnalysisResponse{
			SessionID:  req.SessionID,
			TenantID:   tenantID,
			AnalyzedAt: time.Now(),
		}, nil
	}

	// Build session transcript for LLM analysis
	transcript := buildSessionTranscript(auditLogs)

	resp := &dto.SessionAnalysisResponse{
		SessionID:  req.SessionID,
		TenantID:   tenantID,
		AnalyzedAt: time.Now(),
	}

	if s.openRouter == nil {
		return resp, nil
	}

	// Extract decisions
	includeDecisions := req.IncludeDecisions == nil || *req.IncludeDecisions
	if includeDecisions {
		decisions, err := s.extractDecisions(ctx, transcript)
		if err != nil {
			slog.Warn("failed to extract decisions", "error", err)
		} else {
			resp.Decisions = decisions
			resp.TotalDecisions = len(decisions)
		}
	}

	// Extract insights
	includeInsights := req.IncludeInsights == nil || *req.IncludeInsights
	maxInsights := req.MaxInsights
	if maxInsights <= 0 {
		maxInsights = 10
	}
	if includeInsights {
		insights, err := s.extractInsights(ctx, transcript, maxInsights)
		if err != nil {
			slog.Warn("failed to extract insights", "error", err)
		} else {
			resp.Insights = insights
			resp.TotalInsights = len(insights)
		}
	}

	// Extract failures
	includeFailures := req.IncludeFailures == nil || *req.IncludeFailures
	if includeFailures {
		failures, err := s.extractFailures(ctx, transcript)
		if err != nil {
			slog.Warn("failed to extract failures", "error", err)
		} else {
			resp.Failures = failures
			resp.TotalFailures = len(failures)

			// Auto-create hindsight notes for failures
			go s.createHindsightNotesFromFailures(tenant.WithTenant(context.Background(), tenantID), req.SessionID, failures)
		}
	}

	// Auto-create notes from insights
	if len(resp.Insights) > 0 {
		go s.createNotesFromInsights(tenant.WithTenant(context.Background(), tenantID), req.SessionID, resp.Insights)
	}

	// Auto-create typed session observations
	if s.observationRepo != nil {
		go s.createObservationsFromAnalysis(tenant.WithTenant(context.Background(), tenantID), req.SessionID, resp)
	}

	return resp, nil
}

// GetObservationsBySession returns typed observations for a session.
func (s *NoteTakingService) GetObservationsBySession(ctx context.Context, sessionID string) ([]domain.SessionObservation, error) {
	if s.observationRepo == nil {
		return nil, nil
	}
	return s.observationRepo.FindBySession(ctx, sessionID)
}

// GetObservationsByType returns observations filtered by type.
func (s *NoteTakingService) GetObservationsByType(ctx context.Context, obsType domain.ObservationType, limit int) ([]domain.SessionObservation, error) {
	if s.observationRepo == nil {
		return nil, nil
	}
	return s.observationRepo.FindByType(ctx, obsType, limit)
}

func (s *NoteTakingService) createObservationsFromAnalysis(ctx context.Context, sessionID string, resp *dto.SessionAnalysisResponse) {
	for _, d := range resp.Decisions {
		obs := &domain.SessionObservation{
			SessionID:     sessionID,
			Type:          domain.ObservationDecision,
			Title:         d.Title,
			Description:   d.Description,
			Context:       d.Context,
			AutoGenerated: true,
		}
		if err := s.observationRepo.Create(ctx, obs); err != nil {
			slog.Warn("failed to create decision observation", "error", err)
		}
	}

	for _, ins := range resp.Insights {
		obsType := mapInsightCategoryToObservationType(ins.Category)
		obs := &domain.SessionObservation{
			SessionID:     sessionID,
			Type:          obsType,
			Title:         truncate(ins.Content, 120),
			Description:   ins.Content,
			Context:       ins.RelatedTo,
			AutoGenerated: true,
		}
		if err := s.observationRepo.Create(ctx, obs); err != nil {
			slog.Warn("failed to create insight observation", "error", err)
		}
	}

	for _, f := range resp.Failures {
		obs := &domain.SessionObservation{
			SessionID:     sessionID,
			Type:          domain.ObservationBugfix,
			Title:         fmt.Sprintf("[%s] %s", f.ErrorType, truncate(f.ErrorMessage, 80)),
			Description:   f.Resolution,
			Context:       f.Context,
			AutoGenerated: true,
		}
		if err := s.observationRepo.Create(ctx, obs); err != nil {
			slog.Warn("failed to create failure observation", "error", err)
		}
	}
}

func mapInsightCategoryToObservationType(category string) domain.ObservationType {
	switch category {
	case "ARCHITECTURE":
		return domain.ObservationDecision
	case "DEBUGGING":
		return domain.ObservationBugfix
	case "PERFORMANCE":
		return domain.ObservationRefactor
	default:
		return domain.ObservationDiscovery
	}
}

// CreateHindsightNote creates a manual hindsight note.
func (s *NoteTakingService) CreateHindsightNote(ctx context.Context, req dto.CreateHindsightNoteRequest) (*domain.HindsightNote, error) {
	note := &domain.HindsightNote{
		SessionID:           req.SessionID,
		Title:               fmt.Sprintf("[%s] %s", req.ErrorType, truncate(req.ErrorMessage, 80)),
		Severity:            domain.SeverityMedium,
		ErrorType:           req.ErrorType,
		ErrorMessage:        req.ErrorMessage,
		ErrorContext:        req.ErrorContext,
		Resolution:          req.Resolution,
		ResolutionSteps:     req.ResolutionSteps,
		ResolutionReference: req.ResolutionReference,
		LessonsLearned:      req.LessonsLearned,
		PreventionStrategy:  req.PreventionStrategy,
		Tags:                req.Tags,
		RelatedMemoryIDs:    req.RelatedMemoryIDs,
		Priority:            req.Priority,
		OccurrenceCount:     1,
		AutoGenerated:       false,
	}

	if req.Priority == "HIGH" || req.Priority == "CRITICAL" {
		note.Severity = domain.SeverityHigh
	}

	if err := s.noteRepo.CreateHindsightNote(ctx, note); err != nil {
		return nil, fmt.Errorf("creating hindsight note: %w", err)
	}

	return note, nil
}

// ListNotes returns notes for the current tenant.
func (s *NoteTakingService) ListNotes(ctx context.Context, limit int) ([]domain.Note, error) {
	if limit <= 0 {
		limit = 50
	}
	return s.noteRepo.ListNotes(ctx, limit)
}

// ListHindsightNotes returns hindsight notes for the current tenant.
func (s *NoteTakingService) ListHindsightNotes(ctx context.Context, limit int) ([]domain.HindsightNote, error) {
	if limit <= 0 {
		limit = 50
	}
	return s.noteRepo.ListHindsightNotes(ctx, limit)
}

// GetSessionNotes returns notes for a specific session.
func (s *NoteTakingService) GetSessionNotes(ctx context.Context, sessionID string, limit int) ([]domain.Note, error) {
	if limit <= 0 {
		limit = 50
	}
	return s.noteRepo.FindNotesBySession(ctx, sessionID, limit)
}

// GetSessionHindsight returns hindsight notes for a specific session.
func (s *NoteTakingService) GetSessionHindsight(ctx context.Context, sessionID string, limit int) ([]domain.HindsightNote, error) {
	if limit <= 0 {
		limit = 50
	}
	return s.noteRepo.FindHindsightBySession(ctx, sessionID, limit)
}

func (s *NoteTakingService) extractDecisions(ctx context.Context, transcript string) ([]dto.Decision, error) {
	prompt := fmt.Sprintf(`Analyze the following session transcript and extract key decisions made.
Respond in JSON format only:
{
  "decisions": [
    {
      "title": "brief title",
      "description": "what was decided",
      "rationale": "why this decision was made",
      "context": "surrounding context"
    }
  ]
}

Session transcript:
%s`, truncate(transcript, 4000))

	response, err := s.openRouter.Chat(ctx, []ChatMessage{
		{Role: "system", Content: "You are a session analyst. Extract decisions from development sessions. Respond with valid JSON only."},
		{Role: "user", Content: prompt},
	})
	if err != nil {
		return nil, err
	}

	var result struct {
		Decisions []dto.Decision `json:"decisions"`
	}
	if err := json.Unmarshal([]byte(cleanJSON(response)), &result); err != nil {
		return nil, fmt.Errorf("parsing decisions: %w", err)
	}
	return result.Decisions, nil
}

func (s *NoteTakingService) extractInsights(ctx context.Context, transcript string, maxInsights int) ([]dto.Insight, error) {
	prompt := fmt.Sprintf(`Analyze the following session transcript and extract key insights and learnings.
Maximum %d insights. Respond in JSON format only:
{
  "insights": [
    {
      "category": "ARCHITECTURE|DEBUGGING|PERFORMANCE|SECURITY|BEST_PRACTICE|TOOL_USAGE",
      "content": "the insight",
      "importance": "HIGH|MEDIUM|LOW",
      "relatedTo": "related topic or technology"
    }
  ]
}

Session transcript:
%s`, maxInsights, truncate(transcript, 4000))

	response, err := s.openRouter.Chat(ctx, []ChatMessage{
		{Role: "system", Content: "You are a session analyst. Extract valuable insights from development sessions. Respond with valid JSON only."},
		{Role: "user", Content: prompt},
	})
	if err != nil {
		return nil, err
	}

	var result struct {
		Insights []dto.Insight `json:"insights"`
	}
	if err := json.Unmarshal([]byte(cleanJSON(response)), &result); err != nil {
		return nil, fmt.Errorf("parsing insights: %w", err)
	}
	return result.Insights, nil
}

func (s *NoteTakingService) extractFailures(ctx context.Context, transcript string) ([]dto.FailureInsight, error) {
	prompt := fmt.Sprintf(`Analyze the following session transcript and extract any failures, errors, or issues encountered.
For each failure, suggest a resolution and prevention strategy. Respond in JSON format only:
{
  "failures": [
    {
      "errorType": "type of error",
      "errorMessage": "the error message",
      "context": "when/where it occurred",
      "resolution": "how it was or could be resolved",
      "lessonsLearned": "what to learn from this",
      "preventionHint": "how to prevent it in the future"
    }
  ]
}

Session transcript:
%s`, truncate(transcript, 4000))

	response, err := s.openRouter.Chat(ctx, []ChatMessage{
		{Role: "system", Content: "You are a failure analyst. Extract errors and suggest preventions. Respond with valid JSON only."},
		{Role: "user", Content: prompt},
	})
	if err != nil {
		return nil, err
	}

	var result struct {
		Failures []dto.FailureInsight `json:"failures"`
	}
	if err := json.Unmarshal([]byte(cleanJSON(response)), &result); err != nil {
		return nil, fmt.Errorf("parsing failures: %w", err)
	}
	return result.Failures, nil
}

func (s *NoteTakingService) createHindsightNotesFromFailures(ctx context.Context, sessionID string, failures []dto.FailureInsight) {
	for _, f := range failures {
		note := &domain.HindsightNote{
			SessionID:          sessionID,
			Title:              fmt.Sprintf("[%s] %s", f.ErrorType, truncate(f.ErrorMessage, 80)),
			Severity:           domain.SeverityMedium,
			ErrorType:          f.ErrorType,
			ErrorMessage:       f.ErrorMessage,
			ErrorContext:       f.Context,
			Resolution:         f.Resolution,
			LessonsLearned:     f.LessonsLearned,
			PreventionStrategy: f.PreventionHint,
			OccurrenceCount:    1,
			AutoGenerated:      true,
		}

		if err := s.noteRepo.CreateHindsightNote(ctx, note); err != nil {
			slog.Warn("failed to create auto hindsight note", "error", err)
		}
	}
}

func (s *NoteTakingService) createNotesFromInsights(ctx context.Context, sessionID string, insights []dto.Insight) {
	for _, ins := range insights {
		noteType := domain.NoteInsight
		if ins.Category == "ARCHITECTURE" {
			noteType = domain.NoteArchitecture
		} else if ins.Category == "BEST_PRACTICE" {
			noteType = domain.NotePattern
		}

		note := &domain.Note{
			SessionID:     sessionID,
			Type:          noteType,
			Title:         truncate(ins.Content, 120),
			Content:       ins.Content,
			Category:      domain.NoteCategoryGeneric,
			Severity:      mapImportanceToSeverity(ins.Importance),
			AutoGenerated: true,
		}
		if ins.RelatedTo != "" {
			note.Keywords = []string{ins.RelatedTo}
		}

		if err := s.noteRepo.CreateNote(ctx, note); err != nil {
			slog.Warn("failed to create auto note", "error", err)
		}
	}
}

func buildSessionTranscript(logs []domain.AuditLog) string {
	var sb []byte
	for _, log := range logs {
		entry := fmt.Sprintf("[%s] %s", log.EventType, log.Timestamp.Format(time.RFC3339))
		if log.UserRequest != "" {
			entry += fmt.Sprintf("\nRequest: %s", log.UserRequest)
		}
		if log.ErrorMessage != "" {
			entry += fmt.Sprintf("\nError: %s", log.ErrorMessage)
		}
		if log.Outcome != "" {
			entry += fmt.Sprintf("\nOutcome: %s", log.Outcome)
		}
		entry += "\n---\n"
		sb = append(sb, []byte(entry)...)
	}
	return string(sb)
}

func mapImportanceToSeverity(importance string) domain.NoteSeverity {
	switch importance {
	case "HIGH":
		return domain.SeverityHigh
	case "MEDIUM":
		return domain.SeverityMedium
	default:
		return domain.SeverityLow
	}
}
