package domain

import "time"

// Note represents a generic note for learning and documentation.
type Note struct {
	ID               string       `json:"id" db:"id"`
	TenantID         string       `json:"tenantId" db:"tenant_id"`
	SessionID        string       `json:"sessionId" db:"session_id"`
	Type             NoteType     `json:"type" db:"type"`
	Title            string       `json:"title" db:"title"`
	Content          string       `json:"content" db:"content"`
	Keywords         []string     `json:"keywords,omitempty" db:"-"`
	Category         NoteCategory `json:"category" db:"category"`
	ProjectID        string       `json:"projectId,omitempty" db:"project_id"`
	Severity         NoteSeverity `json:"severity" db:"severity"`
	ErrorPattern     string       `json:"errorPattern,omitempty" db:"error_pattern"`
	CreatedAt        time.Time    `json:"createdAt" db:"created_at"`
	LastAccessedAt   *time.Time   `json:"lastAccessedAt,omitempty" db:"last_accessed_at"`
	LastOccurrenceAt *time.Time   `json:"lastOccurrenceAt,omitempty" db:"last_occurrence_at"`
	AccessCount      int          `json:"accessCount" db:"access_count"`
	RelatedMemoryIDs []string     `json:"relatedMemoryIds,omitempty" db:"-"`
	RelatedNoteIDs   []string     `json:"relatedNoteIds,omitempty" db:"-"`
	CreatedBy        string       `json:"createdBy,omitempty" db:"created_by"`
	AutoGenerated    bool         `json:"autoGenerated" db:"auto_generated"`
}

// HindsightNote tracks errors and their resolutions for learning.
type HindsightNote struct {
	ID                     string       `json:"id" db:"id"`
	TenantID               string       `json:"tenantId" db:"tenant_id"`
	SessionID              string       `json:"sessionId,omitempty" db:"session_id"`
	Title                  string       `json:"title,omitempty" db:"title"`
	ErrorPattern           string       `json:"errorPattern,omitempty" db:"error_pattern"`
	Severity               NoteSeverity `json:"severity" db:"severity"`
	LastAccessedAt         *time.Time   `json:"lastAccessedAt,omitempty" db:"last_accessed_at"`
	AccessCount            int          `json:"accessCount" db:"access_count"`
	ErrorType              string       `json:"errorType,omitempty" db:"error_type"`
	ErrorMessage           string       `json:"errorMessage,omitempty" db:"error_message"`
	ErrorContext           string       `json:"errorContext,omitempty" db:"error_context"`
	Resolution             string       `json:"resolution,omitempty" db:"resolution"`
	ResolutionSteps        string       `json:"resolutionSteps,omitempty" db:"resolution_steps"`
	ResolutionReference    string       `json:"resolutionReference,omitempty" db:"resolution_reference"`
	LessonsLearned         string       `json:"lessonsLearned,omitempty" db:"lessons_learned"`
	PreventionStrategy     string       `json:"preventionStrategy,omitempty" db:"prevention_strategy"`
	Tags                   []string     `json:"tags,omitempty" db:"-"`
	RelatedMemoryIDs       []string     `json:"relatedMemoryIds,omitempty" db:"-"`
	RelatedNoteIDs         []string     `json:"relatedNoteIds,omitempty" db:"-"`
	OccurrenceCount        int          `json:"occurrenceCount" db:"occurrence_count"`
	ReferenceCount         int          `json:"referenceCount" db:"reference_count"`
	PreventionSuccessCount int          `json:"preventionSuccessCount" db:"prevention_success_count"`
	CreatedBy              string       `json:"createdBy,omitempty" db:"created_by"`
	AutoGenerated          bool         `json:"autoGenerated" db:"auto_generated"`
	CreatedAt              time.Time    `json:"createdAt" db:"created_at"`
	UpdatedAt              time.Time    `json:"updatedAt" db:"updated_at"`
	LastOccurrenceAt       *time.Time   `json:"lastOccurrenceAt,omitempty" db:"last_occurrence_at"`
	PreventionVerified     bool         `json:"preventionVerified" db:"prevention_verified"`
	Priority               string       `json:"priority,omitempty" db:"priority"`
}

// SessionObservation represents a typed observation from a session analysis.
type SessionObservation struct {
	ID              string          `json:"id" db:"id"`
	TenantID        string          `json:"tenantId" db:"tenant_id"`
	SessionID       string          `json:"sessionId" db:"session_id"`
	Type            ObservationType `json:"type" db:"type"`
	Title           string          `json:"title" db:"title"`
	Description     string          `json:"description" db:"description"`
	Context         string          `json:"context,omitempty" db:"context"`
	RelatedMemoryID string          `json:"relatedMemoryId,omitempty" db:"related_memory_id"`
	CreatedAt       time.Time       `json:"createdAt" db:"created_at"`
	AutoGenerated   bool            `json:"autoGenerated" db:"auto_generated"`
}

// PreventionEffectiveness returns the ratio of successful preventions.
func (h *HindsightNote) PreventionEffectiveness() float64 {
	if h.OccurrenceCount == 0 {
		return 0
	}
	return float64(h.PreventionSuccessCount) / float64(h.OccurrenceCount)
}
